name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PIUSH }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Debug secrets (remove after confirming it's correct)
      - name: Debug Secrets
        run: echo "DOCKERHUB_PIUSH: ${{ secrets.DOCKERHUB_PIYUSH }}; DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Run tests
      - name: Run Tests
        run: |
          docker compose run --rm app sh -c "python manage.py test"
          
      # Run linting
      - name: Run Linting
        run: |
          docker compose run --rm app sh -c "flake8"
