name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PIYUSH }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 3: Run Tests
      - name: Run Tests
        run: |
          docker compose run --rm app sh -c "python manage.py test"

      # Step 4: Run Linting
      - name: Run Linting
        run: |
          docker compose run --rm app sh -c "flake8"
