name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Run tests
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"

      # Run linting
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
